id = "nightfall-theme"
name = "Nightfall"
version = "0.1.0"
schema_version = 1
authors = ["Andrew Zhuk <andrewzhuk@outlook.com>"]
description = "A warm, vivid color scheme inspired by the colors of daybreak-theme"
repository = "https://github.com/andrewzhuk/nightfall-theme"
